let isoCountries = {
    'AF' : 'Afghanistan',
    'AX' : 'Isole Aland',
    'AL' : 'Albania',
    'DZ' : 'Algeria',
    'AS' : 'Samoa Americane',
    'AD' : 'Andorra',
    'AO' : 'Angola',
    'AI' : 'Anguilla',
    'AQ' : 'Antartide',
    'AG' : 'Antigua e Barbuda',
    'AR' : 'Argentina',
    'AM' : 'Armenia',
    'AW' : 'Aruba',
    'AU' : 'Australia',
    'AT' : 'Austria',
    'AZ' : 'Azerbaijan',
    'BS' : 'Bahamas',
    'BH' : 'Bahrain',
    'BD' : 'Bangladesh',
    'BB' : 'Barbados',
    'BY' : 'Bielorussia',
    'BE' : 'Belgio',
    'BZ' : 'Belize',
    'BJ' : 'Benin',
    'BM' : 'Bermuda',
    'BT' : 'Bhutan',
    'BO' : 'Bolivia',
    'BA' : 'Bosnia ed Erzegovina',
    'BW' : 'Botswana',
    'BV' : 'Isola Bouvet',
    'BR' : 'Brasile',
    'IO' : 'Territorio britannico dell\'Oceano Indiano',
    'BN' : 'Sultanato del Brunei',
    'BG' : 'Bulgaria',
    'BF' : 'Burkina Faso',
    'BI' : 'Burundi',
    'KH' : 'Cambogia',
    'CM' : 'Cameroon',
    'CA' : 'Canada',
    'CV' : 'Capo Verde',
    'KY' : 'Isole Cayman',
    'CF' : 'Repubblica Centrafricana',
    'TD' : 'Chad',
    'CL' : 'Cile',
    'CN' : 'Cina',
    'CX' : 'Isola di Natale',
    'CC' : 'Isole Cocos',
    'CO' : 'Colombia',
    'KM' : 'Comoros',
    'CG' : 'Congo',
    'CD' : 'Repubblica Democratica del Congo',
    'CK' : 'Isole Cook',
    'CR' : 'Costa Rica',
    'CI' : 'Costa d\'Avorio',
    'HR' : 'Croazia',
    'CU' : 'Cuba',
    'CY' : 'Cipro',
    'CZ' : 'Repubblica Ceca',
    'DK' : 'Danimarca',
    'DJ' : 'Gibuti',
    'DM' : 'Dominica',
    'DO' : 'Repubblica Dominicana',
    'EC' : 'Ecuador',
    'EG' : 'Egitto',
    'SV' : 'El Salvador',
    'GQ' : 'Guinea Equatoriale',
    'ER' : 'Eritrea',
    'EE' : 'Estonia',
    'ET' : 'Etiopia',
    'FK' : 'Isole Falkland',
    'FO' : 'Fær Øer',
    'FJ' : 'Fiji',
    'FI' : 'Finlandia',
    'FR' : 'Francia',
    'GF' : 'Guyana francese',
    'PF' : 'Polinesia Francese',
    'TF' : 'Terre australi e antartiche francesi',
    'GA' : 'Gabon',
    'GM' : 'Gambia',
    'GE' : 'Georgia',
    'DE' : 'Germania',
    'GH' : 'Ghana',
    'GI' : 'Gibilterra',
    'GR' : 'Grecia',
    'GL' : 'Groenlandia',
    'GD' : 'Grenada',
    'GP' : 'Guadalupa',
    'GU' : 'Guam',
    'GT' : 'Guatemala',
    'GG' : 'Baliato di Guernsey',
    'GN' : 'Guinea',
    'GW' : 'Guinea-Bissau',
    'GY' : 'Guyana',
    'HT' : 'Haiti',
    'HM' : 'Isole Heard e McDonald',
    'VA' : 'Città del Vaticano',
    'HN' : 'Honduras',
    'HK' : 'Hong Kong',
    'HU' : 'Ungheria',
    'IS' : 'Islanda',
    'IN' : 'India',
    'ID' : 'Indonesia',
    'IR' : 'Iran',
    'IQ' : 'Iraq',
    'IE' : 'Irlanda',
    'IM' : 'Isola di Man',
    'IL' : 'Israele',
    'IT' : 'Italia',
    'JM' : 'Jamaica',
    'JP' : 'Giappone',
    'JE' : 'Jersey',
    'JO' : 'Jordan',
    'KZ' : 'Kazakhstan',
    'KE' : 'Kenya',
    'KI' : 'Kiribati',
    'KR' : 'Korea',
    'KW' : 'Kuwait',
    'KG' : 'Kyrgyzstan',
    'LA' : 'Repubblica Popolare Democratica del Laos',
    'LV' : 'Lettonia',
    'LB' : 'Libano',
    'LS' : 'Lesotho',
    'LR' : 'Liberia',
    'LY' : 'Libia',
    'LI' : 'Liechtenstein',
    'LT' : 'Lituania',
    'LU' : 'Lussemburgo',
    'MO' : 'Macao',
    'MK' : 'Macedonia',
    'MG' : 'Madagascar',
    'MW' : 'Malawi',
    'MY' : 'Malaysia',
    'MV' : 'Maldive',
    'ML' : 'Mali',
    'MT' : 'Malta',
    'MH' : 'Isole Marshall',
    'MQ' : 'Martinica',
    'MR' : 'Mauritania',
    'MU' : 'Mauritius',
    'YT' : 'Mayotte',
    'MX' : 'Mexico',
    'FM' : 'Micronesia',
    'MD' : 'Moldavia',
    'MC' : 'Monaco',
    'MN' : 'Mongolia',
    'ME' : 'Montenegro',
    'MS' : 'Montserrat',
    'MA' : 'Marocco',
    'MZ' : 'Mozambico',
    'MM' : 'Myanmar',
    'NA' : 'Namibia',
    'NR' : 'Nauru',
    'NP' : 'Nepal',
    'NL' : 'Paesi Bassi',
    'AN' : 'Antille Olandesi',
    'NC' : 'Nuova Caledonia',
    'NZ' : 'Nuova Zelanda',
    'NI' : 'Nicaragua',
    'NE' : 'Niger',
    'NG' : 'Nigeria',
    'NU' : 'Niue',
    'NF' : 'Isola Norfolk',
    'MP' : 'Isole Marianne Settentrionali',
    'NO' : 'Norvegia',
    'OM' : 'Oman',
    'PK' : 'Pakistan',
    'PW' : 'Palau',
    'PS' : 'Territori palestinesi',
    'PA' : 'Panama',
    'PG' : 'Papua Nuova Guinea',
    'PY' : 'Paraguay',
    'PE' : 'Perù',
    'PH' : 'Philippine',
    'PN' : 'Isole Pitcairn',
    'PL' : 'Polonia',
    'PT' : 'Portogallo',
    'PR' : 'Puerto Rico',
    'QA' : 'Qatar',
    'RE' : 'Riunione',
    'RO' : 'Romania',
    'RU' : 'Russia',
    'RW' : 'Rwanda',
    'BL' : 'Saint-Barthélemy',
    'SH' : 'Sant\'Elena',
    'KN' : 'Saint Kitts e Nevis',
    'LC' : 'Santa Lucia',
    'MF' : 'San Martino',
    'PM' : 'Saint-Pierre e Miquelon',
    'VC' : 'Saint Vincent e Grenadine',
    'WS' : 'Samoa',
    'SM' : 'San Marino',
    'ST' : 'São Tomé e Príncipe',
    'SA' : 'Arabia Saudita',
    'SN' : 'Senegal',
    'RS' : 'Serbia',
    'SC' : 'Seychelles',
    'SL' : 'Sierra Leone',
    'SG' : 'Singapore',
    'SK' : 'Slovacchia',
    'SI' : 'Slovenia',
    'SB' : 'Isole Salomone',
    'SO' : 'Somalia',
    'ZA' : 'Sudafrica',
    'GS' : 'Georgia del Sud',
    'ES' : 'Spagna',
    'LK' : 'Sri Lanka',
    'SD' : 'Sudan',
    'SR' : 'Suriname',
    'SJ' : 'Svalbard e Jan Mayen',
    'SZ' : 'Swaziland',
    'SE' : 'Svezia',
    'CH' : 'Svizzera',
    'SY' : 'Siria',
    'TW' : 'Taiwan',
    'TJ' : 'Tajikistan',
    'TZ' : 'Tanzania',
    'TH' : 'Thailandia',
    'TL' : 'Timor Est',
    'TG' : 'Togo',
    'TK' : 'Tokelau',
    'TO' : 'Tonga',
    'TT' : 'Trinidad e Tobago',
    'TN' : 'Tunisia',
    'TR' : 'Turchia',
    'TM' : 'Turkmenistan',
    'TC' : 'Turks e Caicos',
    'TV' : 'Tuvalu',
    'UG' : 'Uganda',
    'UA' : 'Ukraina',
    'AE' : 'Emirati Arabi Uniti',
    'GB' : 'Regno Unito',
    'US' : 'Stati Uniti d\'America',
    'UM' : 'Isole minori esterne degli Stati Uniti d\'America',
    'UY' : 'Uruguay',
    'UZ' : 'Uzbekistan',
    'VU' : 'Vanuatu',
    'VE' : 'Venezuela',
    'VN' : 'Vietnam',
    'VG' : 'Isole Vergini britanniche',
    'VI' : 'Isole Vergini americane',
    'WF' : 'Wallis e Futuna',
    'EH' : 'Sahara Occidentale',
    'YE' : 'Yemen',
    'ZM' : 'Zambia',
    'ZW' : 'Zimbabwe'
};

let isoCountriesRev = {
    'Afghanistan': 'AF',
    'Aland Islands': 'AX',
    'Albania': 'AL',
    'Algeria': 'DZ',
    'American Samoa': 'AS',
    'Andorra': 'AD',
    'Angola': 'AO',
    'Anguilla': 'AI',
    'Antarctica': 'AQ',
    'Antigua And Barbuda': 'AG',
    'Argentina': 'AR',
    'Armenia': 'AM',
    'Aruba': 'AW',
    'Australia': 'AU',
    'Austria': 'AT',
    'Azerbaijan': 'AZ',
    'Bahamas': 'BS',
    'Bahrain': 'BH',
    'Bangladesh': 'BD',
    'Barbados': 'BB',
    'Belarus': 'BY',
    'Belgium': 'BE',
    'Belize': 'BZ',
    'Benin': 'BJ',
    'Bermuda': 'BM',
    'Bhutan': 'BT',
    'Bolivia': 'BO',
    'Bosnia And Herzegovina': 'BA',
    'Botswana': 'BW',
    'Bouvet Island': 'BV',
    'Brazil': 'BR',
    'British Indian Ocean Territory': 'IO',
    'Brunei Darussalam': 'BN',
    'Bulgaria': 'BG',
    'Burkina Faso': 'BF',
    'Burundi': 'BI',
    'Cambodia': 'KH',
    'Cameroon': 'CM',
    'Canada': 'CA',
    'Cape Verde': 'CV',
    'Cayman Islands': 'KY',
    'Central African Republic': 'CF',
    'Chad': 'TD',
    'Chile': 'CL',
    'China': 'CN',
    'Christmas Island': 'CX',
    'Cocos (Keeling) Islands': 'CC',
    'Colombia': 'CO',
    'Comoros': 'KM',
    'Congo': 'CG',
    'Congo, Democratic Republic': 'CD',
    'Cook Islands': 'CK',
    'Costa Rica': 'CR',
    'Cote D\'Ivoire': 'CI',
    'Croatia': 'HR',
    'Cuba': 'CU',
    'Cyprus': 'CY',
    'Czech Republic': 'CZ',
    'Denmark': 'DK',
    'Djibouti': 'DJ',
    'Dominica': 'DM',
    'Dominican Republic': 'DO',
    'Ecuador': 'EC',
    'Egypt': 'EG',
    'El Salvador': 'SV',
    'Equatorial Guinea': 'GQ',
    'Eritrea': 'ER',
    'Estonia': 'EE',
    'Ethiopia': 'ET',
    'Falkland Islands': 'FK',
    'Faroe Islands': 'FO',
    'Fiji': 'FJ',
    'Finland': 'FI',
    'France': 'FR',
    'French Guiana': 'GF',
    'French Polynesia': 'PF',
    'French Southern Territories': 'TF',
    'Gabon': 'GA',
    'Gambia': 'GM',
    'Georgia': 'GE',
    'Germany': 'DE',
    'Ghana': 'GH',
    'Gibraltar': 'GI',
    'Greece': 'GR',
    'Greenland': 'GL',
    'Grenada': 'GD',
    'Guadeloupe': 'GP',
    'Guam': 'GU',
    'Guatemala': 'GT',
    'Guernsey': 'GG',
    'Guinea': 'GN',
    'Guinea-Bissau': 'GW',
    'Guyana': 'GY',
    'Haiti': 'HT',
    'Heard Island & Mcdonald Islands': 'HM',
    'Holy See (Vatican City State)': 'VA',
    'Honduras': 'HN',
    'Hong Kong': 'HK',
    'Hungary': 'HU',
    'Iceland': 'IS',
    'India': 'IN',
    'Indonesia': 'ID',
    'Iran, Islamic Republic Of': 'IR',
    'Iraq': 'IQ',
    'Ireland': 'IE',
    'Isle Of Man': 'IM',
    'Israel': 'IL',
    'Italy': 'IT',
    'Jamaica': 'JM',
    'Japan': 'JP',
    'Jersey': 'JE',
    'Jordan': 'JO',
    'Kazakhstan': 'KZ',
    'Kenya': 'KE',
    'Kiribati': 'KI',
    'Korea': 'KR',
    'Kuwait': 'KW',
    'Kyrgyzstan': 'KG',
    'Lao People\'s Democratic Republic': 'LA',
    'Latvia': 'LV',
    'Lebanon': 'LB',
    'Lesotho': 'LS',
    'Liberia': 'LR',
    'Libyan Arab Jamahiriya': 'LY',
    'Liechtenstein': 'LI',
    'Lithuania': 'LT',
    'Luxembourg': 'LU',
    'Macao': 'MO',
    'Macedonia': 'MK',
    'Madagascar': 'MG',
    'Malawi': 'MW',
    'Malaysia': 'MY',
    'Maldives': 'MV',
    'Mali': 'ML',
    'Malta': 'MT',
    'Marshall Islands': 'MH',
    'Martinique': 'MQ',
    'Mauritania': 'MR',
    'Mauritius': 'MU',
    'Mayotte': 'YT',
    'Mexico': 'MX',
    'Micronesia, Federated States Of': 'FM',
    'Moldova': 'MD',
    'Monaco': 'MC',
    'Mongolia': 'MN',
    'Montenegro': 'ME',
    'Montserrat': 'MS',
    'Morocco': 'MA',
    'Mozambique': 'MZ',
    'Myanmar': 'MM',
    'Namibia': 'NA',
    'Nauru': 'NR',
    'Nepal': 'NP',
    'Netherlands': 'NL',
    'Netherlands Antilles': 'AN',
    'New Caledonia': 'NC',
    'New Zealand': 'NZ',
    'Nicaragua': 'NI',
    'Niger': 'NE',
    'Nigeria': 'NG',
    'Niue': 'NU',
    'Norfolk Island': 'NF',
    'Northern Mariana Islands': 'MP',
    'Norway': 'NO',
    'Oman': 'OM',
    'Pakistan': 'PK',
    'Palau': 'PW',
    'Palestinian Territory, Occupied': 'PS',
    'Panama': 'PA',
    'Papua New Guinea': 'PG',
    'Paraguay': 'PY',
    'Peru': 'PE',
    'Philippines': 'PH',
    'Pitcairn': 'PN',
    'Poland': 'PL',
    'Portugal': 'PT',
    'Puerto Rico': 'PR',
    'Qatar': 'QA',
    'Reunion': 'RE',
    'Romania': 'RO',
    'Russian Federation': 'RU',
    'Rwanda': 'RW',
    'Saint Barthelemy': 'BL',
    'Saint Helena': 'SH',
    'Saint Kitts And Nevis': 'KN',
    'Saint Lucia': 'LC',
    'Saint Martin': 'MF',
    'Saint Pierre And Miquelon': 'PM',
    'Saint Vincent And Grenadines': 'VC',
    'Samoa': 'WS',
    'San Marino': 'SM',
    'Sao Tome And Principe': 'ST',
    'Saudi Arabia': 'SA',
    'Senegal': 'SN',
    'Serbia': 'RS',
    'Seychelles': 'SC',
    'Sierra Leone': 'SL',
    'Singapore': 'SG',
    'Slovakia': 'SK',
    'Slovenia': 'SI',
    'Solomon Islands': 'SB',
    'Somalia': 'SO',
    'South Africa': 'ZA',
    'South Georgia And Sandwich Isl.': 'GS',
    'Spain': 'ES',
    'Sri Lanka': 'LK',
    'Sudan': 'SD',
    'Suriname': 'SR',
    'Svalbard And Jan Mayen': 'SJ',
    'Swaziland': 'SZ',
    'Sweden': 'SE',
    'Switzerland': 'CH',
    'Syrian Arab Republic': 'SY',
    'Taiwan': 'TW',
    'Tajikistan': 'TJ',
    'Tanzania': 'TZ',
    'Thailand': 'TH',
    'Timor-Leste': 'TL',
    'Togo': 'TG',
    'Tokelau': 'TK',
    'Tonga': 'TO',
    'Trinidad And Tobago': 'TT',
    'Tunisia': 'TN',
    'Turkey': 'TR',
    'Turkmenistan': 'TM',
    'Turks And Caicos Islands': 'TC',
    'Tuvalu': 'TV',
    'Uganda': 'UG',
    'Ukraine': 'UA',
    'United Arab Emirates': 'AE',
    'United Kingdom': 'GB',
    'United States': 'US',
    'United States Outlying Islands': 'UM',
    'Uruguay': 'UY',
    'Uzbekistan': 'UZ',
    'Vanuatu': 'VU',
    'Venezuela': 'VE',
    'Vietnam': 'VN',
    'Virgin Islands, British': 'VG',
    'Virgin Islands, U.S.': 'VI',
    'Wallis And Futuna': 'WF',
    'Western Sahara': 'EH',
    'Yemen': 'YE',
    'Zambia': 'ZM',
    'Zimbabwe': 'ZW'
};

let months = ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno',
              'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'];
let engmonths = ['Gen', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];

module.exports = {
  months,
  engmonths,
  capWord: function (word) {
    word = word.charAt(0).toUpperCase() + word.substr(1);
    for (let i = 0; i < word.length; i++) {
      if (word.charAt(i) == ' ') {
        word = word.toLowerCase()
          .split(' ')
          .map((s) => s.charAt(0).toUpperCase() + s.substring(1))
          .join(' ');
      }
    }
    return word;
  },
  enUSConv: function (date) {
    let a = new Date(date.replace(/,/g, ""));
    let year = a.getFullYear();
    let month = months[a.getMonth()];
    let day = a.getDate();
    let time = day + ' ' + month + ' ' + year;
    return time;
  },
  isValidDate: function (date) {
    if (!/^\d{1,2}\/\d{1,2}\/\d{4}$/.test(date)) return false;
    var parts = date.split("/");
    var day = parseInt(parts[0], 10);
    var month = parseInt(parts[1], 10);
    var year = parseInt(parts[2], 10);
    if (year < 1900 || year > new Date().getFullYear() || month <= 0 || month > 12) return false;
    var monthLength = [31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
    if (year % 400 == 0 || (year % 100 != 0 && year % 4 == 0)) monthLength[1] = 29;
    if (day < 1 || day > monthLength[month - 1]) return false;
    return true;
  },
  IsoConv: function (timestamp) {
    let a = new Date(timestamp);
    let year = a.getFullYear();
    let month = months[a.getMonth()];
    let day = a.getDate();
    let hour = a.getHours();
    let min = a.getMinutes();
    let sec = a.getSeconds();
    if (hour < 10) hour = "0" + hour;
    if (min < 10) min = "0" + min;
    if (sec < 10) sec = "0" + sec;
    let time = day + ' ' + month + ' ' + year + ' alle ' + hour + ':' + min + ':' + sec;
    return time;
  },
  SRKTourDate: function (timestamp) {
    let a = new Date(timestamp);
    let year = a.getFullYear();
    let month = months[a.getMonth()];
    let day = a.getDate();
    if (day < 10) day = "0" + day;
    let time = day + ' ' + month + ' ' + year;
    return time;
  },
  UnixConv: function (timestamp) {
    let a = new Date(timestamp * 1000);
    let year = a.getFullYear();
    let month = months[a.getMonth()];
    let day = a.getDate();
    let hour = a.getHours();
    let min = a.getMinutes();
    let sec = a.getSeconds();
    if (day < 10) day = "0" + day;
    if (hour < 10) hour = "0" + hour;
    if (min < 10) min = "0" + min;
    if (sec < 10) sec = "0" + sec;
    let time = day + ' ' + month + ' ' + year + ' alle ' + hour + ':' + min + ':' + sec ;
    return time;
  },
  getCountryName: function (countryCode) {
    if (isoCountries.hasOwnProperty(countryCode)) return isoCountries[countryCode];
    else return countryCode;
  },
  getCountryCode: function (countryName) {
    if (isoCountriesRev.hasOwnProperty(countryName)) return isoCountriesRev[countryName];
    else return countryName;
  }
};